/**
 * @file       bsp_rc522.c
 * @copyright  Copyright (C) 2025
 * @license    This project is released under the Fiot License.
 * @version    1.0.0
 * @date       2025
 * @author     Bao Quoc
 *
 * @brief      Implementation of MFRC522 RFID Board Support Package (BSP) for STM32F1
 *
 * @note       Tested on STM32F103C8T6 using CubeIDE + HAL
 * @example    main.c
 *             Example of using MFRC522_Check() to read card UID
 */

/* Includes ----------------------------------------------------------- */
#include "bsp_rc522.h"
#include "main.h"   /**< For HAL and GPIO defines */
#include <string.h> /**< For memcmp/memset */

/* Private defines ---------------------------------------------------- */
/* Private enumerate/structure ---------------------------------------- */
/* Private macros ----------------------------------------------------- */
/* Public variables --------------------------------------------------- */
/* Private variables -------------------------------------------------- */

SPI_HandleTypeDef BSP_RFID_SPI_HANDLE;

static rfid_handle_t rfid_handle;       /**< Handle for the RFID driver */
static rfid_io_t rfid_io_binding;       /**< Structure to bind I/O functions */
static bool bsp_is_initialized = false; /**< Flag to ensure single init */
static uint8_t last_detected_uid[MFRC522_UID_SIZE] = {0}; /**< Buffer for last UID */

/* Private function prototypes (Hardware Abstraction Layer Wrappers)---- */

/**
 * @brief  Wrapper function for HAL SPI transmit.
 * @param[in]  data Pointer to the data buffer to be transmitted.
 * @param[in]  size Amount of data to be transmitted in bytes.
 */
static void bsp_spi_transmit(uint8_t* data, uint16_t size);

/**
 * @brief  Wrapper function for HAL SPI receive.
 * @param[out] data Pointer to the data buffer to store received data.
 * @param[in]  size Amount of data to be received in bytes.
 */
static void bsp_spi_receive(uint8_t* data, uint16_t size);

/**
 * @brief  Wrapper function for HAL SPI transmit-receive.
 * @param[in]  tx_data Pointer to the transmission data buffer.
 * @param[out] rx_data Pointer to the reception data buffer.
 * @param[in]  size    Amount of data to be sent and received in bytes.
 */
static void bsp_spi_transmit_receive(uint8_t* tx_data, uint8_t* rx_data, uint16_t size);

/**
 * @brief  Pulls the Chip Select (CS) pin to a low state.
 */
static void bsp_cs_low(void);

/**
 * @brief  Pulls the Chip Select (CS) pin to a high state.
 */
static void bsp_cs_high(void);

/**
 * @brief  Pulls the Reset (RST) pin to a low state.
 */
static void bsp_reset_low(void);

/**
 * @brief  Pulls the Reset (RST) pin to a high state.
 */
static void bsp_reset_high(void);

/**
 * @brief  Initializes the low-level hardware (GPIO, SPI) required for the RFID module.
 * @return rfid_status_t - RFID_STATUS_OK on success, RFID_STATUS_ERROR on failure.
 */
static rfid_status_t bsp_rfid_hw_init(void);

/* Public implementations --------------------------------------------------- */

rfid_status_t bsp_rfid_init(void)
{
    if (bsp_is_initialized)
    {
        return RFID_STATUS_OK;
    }

    // Step 1: Initialize the low-level hardware (clocks, pins, SPI)
    // These functions are generated by CubeMX and contain HAL calls
    if (bsp_rfid_hw_init() != RFID_STATUS_OK)
    {
        return RFID_STATUS_ERROR; // Report error if hardware init fails
    }

    // Step 2: Bind the HAL functions to our IO structure
    rfid_io_binding.spi_transmit = bsp_spi_transmit;
    rfid_io_binding.spi_receive = bsp_spi_receive;
    rfid_io_binding.spi_transmit_receive = bsp_spi_transmit_receive;
    rfid_io_binding.cs_low = bsp_cs_low;
    rfid_io_binding.cs_high = bsp_cs_high;
    rfid_io_binding.reset_low = bsp_reset_low;
    rfid_io_binding.reset_high = bsp_reset_high;
    rfid_io_binding.delay_ms = HAL_Delay;

    // Step 3: Initialize the driver, "injecting" the IO functions
    rfid_status_t status = rfid_init(&rfid_handle, &rfid_io_binding);

    if (status == RFID_STATUS_OK)
    {
        bsp_is_initialized = true;
    }

    return status;
}

bool bsp_rfid_check_for_new_card(uint8_t* uid)
{
    if ((!bsp_is_initialized) || (uid == NULL))
    {
        return false;
    }

    uint8_t current_uid[MFRC522_UID_SIZE];

    if (rfid_check_card(&rfid_handle, current_uid) == RFID_STATUS_OK)
    {
        // A card is present. Check if it's a new one.
        if (memcmp(current_uid, last_detected_uid, MFRC522_UID_SIZE) != 0)
        {
            // It's a new card!
            memcpy(uid, current_uid, MFRC522_UID_SIZE);
            memcpy(last_detected_uid, current_uid, MFRC522_UID_SIZE);
            return true;
        }
    }

    else
    {
        // No card is present, reset the last UID to detect the same card again
        memset(last_detected_uid, 0, MFRC522_UID_SIZE);
    }

    return false;
}

/* Private implementations -------------------------------------------------- */

static void bsp_spi_transmit(uint8_t* data, uint16_t size)
{
    HAL_SPI_Transmit(&BSP_RFID_SPI_HANDLE, data, size, HAL_MAX_DELAY);
}

static void bsp_spi_receive(uint8_t* data, uint16_t size)
{
    HAL_SPI_Receive(&BSP_RFID_SPI_HANDLE, data, size, HAL_MAX_DELAY);
}

static void bsp_spi_transmit_receive(uint8_t* tx_data, uint8_t* rx_data, uint16_t size)
{
    HAL_SPI_TransmitReceive(&BSP_RFID_SPI_HANDLE, tx_data, rx_data, size, HAL_MAX_DELAY);
}

static void bsp_cs_low(void)
{
    HAL_GPIO_WritePin(BSP_RFID_CS_PORT, BSP_RFID_CS_PIN, GPIO_PIN_RESET);
}

static void bsp_cs_high(void)
{
    HAL_GPIO_WritePin(BSP_RFID_CS_PORT, BSP_RFID_CS_PIN, GPIO_PIN_SET);
}

static void bsp_reset_low(void)
{
    HAL_GPIO_WritePin(BSP_RFID_RST_PORT, BSP_RFID_RST_PIN, GPIO_PIN_RESET);
}

static void bsp_reset_high(void)
{
    HAL_GPIO_WritePin(BSP_RFID_RST_PORT, BSP_RFID_RST_PIN, GPIO_PIN_SET);
}

static rfid_status_t bsp_rfid_hw_init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    // --- GPIO Configuration ---
    /* GPIO Ports Clock Enable */
    BSP_RFID_CS_GPIO_CLK_ENABLE();
    BSP_RFID_RST_GPIO_CLK_ENABLE();
    BSP_RFID_IRQ_GPIO_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();
    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_RESET);
      /*Configure GPIO pin : PC13 */
      GPIO_InitStruct.Pin = GPIO_PIN_13;
      GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
      GPIO_InitStruct.Pull = GPIO_NOPULL;
      GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
      HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);

    /*Configure GPIO pin Output Level to high to avoid glitches during startup */
    HAL_GPIO_WritePin(BSP_RFID_CS_PORT, BSP_RFID_CS_PIN, GPIO_PIN_SET);
    HAL_GPIO_WritePin(BSP_RFID_RST_PORT, BSP_RFID_RST_PIN, GPIO_PIN_SET);

    /*Configure GPIO pin : CS Pin */
    GPIO_InitStruct.Pin = BSP_RFID_CS_PIN;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(BSP_RFID_CS_PORT, &GPIO_InitStruct);

    /*Configure GPIO pin : RST Pin */
    GPIO_InitStruct.Pin = BSP_RFID_RST_PIN;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(BSP_RFID_RST_PORT, &GPIO_InitStruct);

    /*Configure GPIO pin : IRQ Pin */
    GPIO_InitStruct.Pin = BSP_RFID_IRQ_PIN;
    GPIO_InitStruct.Mode = GPIO_MODE_IT_FALLING;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(BSP_RFID_IRQ_PORT, &GPIO_InitStruct);

    /* EXTI interrupt init*/
    HAL_NVIC_SetPriority(BSP_RFID_IRQn, 1, 0);
    HAL_NVIC_EnableIRQ(BSP_RFID_IRQn);

    // --- SPI Configuration ---
    BSP_RFID_SPI_HANDLE.Instance = BSP_RFID_SPI_INSTANCE;
    BSP_RFID_SPI_HANDLE.Init.Mode = SPI_MODE_MASTER;
    BSP_RFID_SPI_HANDLE.Init.Direction = SPI_DIRECTION_2LINES;
    BSP_RFID_SPI_HANDLE.Init.DataSize = SPI_DATASIZE_8BIT;
    BSP_RFID_SPI_HANDLE.Init.CLKPolarity = SPI_POLARITY_LOW;
    BSP_RFID_SPI_HANDLE.Init.CLKPhase = SPI_PHASE_1EDGE;
    BSP_RFID_SPI_HANDLE.Init.NSS = SPI_NSS_SOFT;
    BSP_RFID_SPI_HANDLE.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_16;
    BSP_RFID_SPI_HANDLE.Init.FirstBit = SPI_FIRSTBIT_MSB;
    BSP_RFID_SPI_HANDLE.Init.TIMode = SPI_TIMODE_DISABLE;
    BSP_RFID_SPI_HANDLE.Init.CRCCalculation = SPI_CRCCALCULATION_DISABLE;
    BSP_RFID_SPI_HANDLE.Init.CRCPolynomial = 10;
    if (HAL_SPI_Init(&BSP_RFID_SPI_HANDLE) != HAL_OK)
    {
        return RFID_STATUS_ERROR;
    }

    return RFID_STATUS_OK;
}

void HAL_SPI_MspInit(SPI_HandleTypeDef* spiHandle)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};
    if(spiHandle->Instance == BSP_RFID_SPI_INSTANCE)
    {
        /* SPI peripheral clock enable */
        BSP_RFID_SPI_CLK_ENABLE();
        /* GPIO port for SPI clock enable */
        BSP_RFID_SPI_GPIO_CLK_ENABLE();

        /**SPI1 GPIO Configuration    */
        GPIO_InitStruct.Pin = BSP_RFID_SPI_SCK_PIN | BSP_RFID_SPI_MOSI_PIN;
        GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
        GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
        HAL_GPIO_Init(BSP_RFID_SPI_GPIO_PORT, &GPIO_InitStruct);

        GPIO_InitStruct.Pin = BSP_RFID_SPI_MISO_PIN;
        GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
        GPIO_InitStruct.Pull = GPIO_NOPULL;
        HAL_GPIO_Init(BSP_RFID_SPI_GPIO_PORT, &GPIO_InitStruct);
    }
}

/* End of file -------------------------------------------------------- */
